### ISSUE TITLE
Hack Issue ?

### ISSUE THREAD

**Issue by bmwm69** [ghoost82/mijia-720p-hack#1]
Hello,

I already formated sd card in fat32 and copy all content of the /mijia-720p-hack/sdcard/ folder at the root of your memory card.

But after boot I have blue light and acess from MI Home APP but dont have acess to http://ip or telnet , whats wrong ? My camera have last firmware.

**Comment by bmwm69** [comment]
Firmware version 3.3.6_2017111315

**Comment by haimn** [comment]
On version 3.3.6_2017111315 too, the hack is not working for me either.
If you need logs/ more info, I'll be happy to help.

**Comment by ghoost82** [comment]
Currently my Mijia is running on 3.3.6_2017070413. I will check the latest update for any changes that will prevent the hack to work.

**Comment by bmwm69** [comment]
@ghoost82 Thanks for your work ! If you need logs I can also help.

**Comment by haimn** [comment]
@ghoost82 thanks!
The hack will help me a lot.

**Comment by ghoost82** [comment]
I have checked the latest firmware version and there are no changes to prevent the hack.
But there was a bug in the manufacture.bin that prevent the bootstraping, this is now fixed.
I also uploaded a release with precompiled binaries.
Please check and let me know if you find any bugs.

**Comment by bmwm69** [comment]
@ghoost82 already works !! Tks

**Comment by haimn** [comment]
Thanks! I'll check it out and update.

**Comment by welby78** [comment]
Can't seem to get it working on the latest firmware?

**Comment by esabea** [comment]
@bmwm69 How did you manage to make it work?
My firmware is 3.3.6_2017111315

**Comment by haimn** [comment]
It worked for me too.
I just downloaded the release zip and put it's content in the SD card.
https://github.com/ghoost82/mijia-720p-hack/releases

**Comment by esabea** [comment]
thank you @haimn....I had not previously downloaded the manufacture.bin file

**Comment by welby78** [comment]
I got it to work once with the release zip but couldn't view anything via rtsp. Now it won't work again.

**Comment by ghoost82** [comment]
Hi,

as it seems that the hack is working for all of you I will close this issue.

Regards
-jan

**Comment by Danillocl** [comment]
Hello, my camera is the latest model Xiaomi Mijia Smart 1080P PTZ (MJSX02CM), I am having problems with the Yellow LED caught. Where can I find the firmware for my camera?
