### ISSUE TITLE
RTSP password

### ISSUE THREAD

**Issue by daisakute** [ghoost82/mijia-720p-hack#23]
Is it posible to set up a password to protect the rtsp stream over the internet, i hacked the cam to access it from when im away home but dont want to let it open in the internet so everyone see me dancing naked, is a severe security issue.

**Comment by carlosen14** [comment]
you can see the script where the rtsp is created, and see what command uses and inspect which are the options necessary to configure for your specific case.

**apart**..
now that it is hacked, are you still able to control the cam using the arrows? How do you see the cam from outside your local network?

**Comment by carlosen14** [comment]
i think it is using [this](http://www.cs.columbia.edu/irt/cinema/doc/rtspd.html) and it does not provide a configuration to set auth.

**Comment by daisakute** [comment]
It seems like you said, its not possible to set auth in the rtsp server used so i just set up a vpn and send the video over it.

**Comment by carlosen14** [comment]
would you explain a bit how to do it? or which software you used?

**Comment by vladimirovsan** [comment]
I want to access RSTP, I have not yet obtained. What firmware did you use?
What settings did you use?

**Comment by carlosen14** [comment]
@vladimirovsan 
To configure [here](https://github.com/ghoost82/mijia-720p-hack#configure-the-mijia-camera-on-the-memory-card)  
To use the cam [here](https://github.com/ghoost82/mijia-720p-hack#rtsp-server)

**Comment by carlosen14** [comment]
this should be marked as closed!

**Comment by vladimirovsan** [comment]
where can I write?
create a new topic?

**Comment by vladimirovsan** [comment]
I want to receive RSTP stream in vMix

**Comment by carlosen14** [comment]
a new issue

**Comment by vladimirovsan** [comment]
the camera accepts file settings, but vMix or VLC does not see the RSTP / stream
latest camera firmware

**Comment by vladimirovsan** [comment]
rtsp://192.168.1.31/live/ch00_0   no work

**Comment by vladimirovsan** [comment]
http://192.168.1.31/ no work
