### ISSUE TITLE
GM8136 SDK toolchain

### ISSUE THREAD

**Issue by dmcarrero** [ghoost82/mijia-720p-hack#7]
Following the procedure:
To build the binaries the GM8136 SDK toolchain must be installed in /usr/src/arm-linux-3.3/toolchain_gnueabi-4.4.
0_ARMv5TE

How can I install it in Linux Mint??

Thanks!

**Comment by dmcarrero** [comment]
sorry I downloaded a pre compiled version

**Comment by ricardojlrufino** [comment]
https://github.com/Filipowicz251/mijia-1080P-hacks/wiki
