### ISSUE TITLE
DISABLE_CLOUD_STREAMING=1 I cannot manage the device from App

### ISSUE THREAD

**Issue by dmcarrero** [ghoost82/mijia-720p-hack#8]
Hi,

This is the configuration I got:
## Start syslog (0/1)
ENABLE_SYSLOG=1
## Total Disconnect from Xioami servers, includes disable of streaming and OTA updater (0/1)
DISABLE_CLOUD=0
## Manage the camera via cloud but don't stream anything outside your network (0/1)
DISABLE_CLOUD_STREAMING=1
## Manage the camera via cloud but prevent online updates (0/1)
DISABLE_OTA=1

I cannot manage the camera from iphone App, Mi Home App is not able to connect, it shows device offline.

How can I configure features like disable "24-hour auto recording" or save to NAS Server?

Thanks in advance!

**Comment by ghoost82** [comment]
Hello,

looks like there are some control functions in the streaming app. This means it is not possible to disable the cloud streaming. In a new release I'm currently preparing there is only on disable cloud option to make this clear.
